# %%
import numpy as np
from typing import Any
from scipy import sparse


# TODO: implement the PCA with numpy
# Note that you are not allowed to use any existing PCA implementation from sklearn or other libraries.
class PrincipalComponentAnalysis:
    def __init__(self, n_components: int) -> None:
        """_summary_

        Parameters
        ----------
        n_components : int
            The number of principal components to be computed. This value should be less than or equal to the number of features in the dataset.
        """
        self.n_components = n_components
        self.components = None
        self.mean = None

    # TODO: implement the fit method
    def fit(self, X: np.ndarray):
        """
        Fit the model with X.

        Parameters
        ----------
        X : ndarray of shape (n_samples, n_features)
            Training data, where n_samples is the number of samples
            and n_features is the number of features.

        Returns
        -------
        self : object
            Returns the instance itself.
        """
        self.mean = np.mean(X, axis=0)
        Xc = X - self.mean
        Cov = Xc.T @ Xc / (Xc.shape[0] - 1)
        lam, v = np.linalg.eig(Cov)
        order = np.argsort(-lam)[: self.n_components]
        self.components = v[:, order]

        return self

    def transform(self, X: np.ndarray) -> np.ndarray:
        """
        Apply dimensionality reduction to X.

        X is projected on the first principal components previously extracted from a training set.

        Parameters
        ----------
        X : ndarray of shape (n_samples, n_features)
            New data, where n_samples is the number of samples
            and n_features is the number of features.

        Returns
        -------
        X_new : ndarray of shape (n_samples, n_components)
            Transformed values.
        """
        Xc = X - self.mean
        X_new = Xc @ self.components

        return X_new


# TODO: implement the LDA with numpy
# Note that you are not allowed to use any existing LDA implementation from sklearn or other libraries.
class LinearDiscriminantAnalysis:
    def __init__(self, n_components: int) -> None:
        self.n_components = n_components
        self.components = None
        self.mean = None

    def fit(self, X: np.ndarray, y: np.ndarray):
        """
        Fit the model according to the given training data.

        Parameters
        ----------
        X : ndarray of shape (n_samples, n_features)
            Training data, where n_samples is the number of samples
            and n_features is the number of features.
        y : ndarray of shape (n_samples,)
            Target values.

        Returns
        -------
        self : object
            Returns the instance itself.

        Hint:
        -----
        To implement LDA with numpy, follow these steps:
        1. Compute the mean vectors for each class.
        2. Compute the within-class scatter matrix.
        3. Compute the between-class scatter matrix.
        4. Compute the eigenvectors and corresponding eigenvalues for the scatter matrices.
        5. Sort the eigenvectors by decreasing eigenvalues and choose k eigenvectors with the largest eigenvalues to form a d×k dimensional matrix W.
        6. Use this d×k eigenvector matrix to transform the samples onto the new subspace.
        """
        yclass = np.unique(y)
        Sw = np.zeros((X.shape[1], X.shape[1]))
        Sb = np.zeros((X.shape[1], X.shape[1]))
        self.mean = np.mean(X, axis=0)
        Xc = X - np.mean(X)

        for yc in yclass:
            Xclass = X[y == yc]
            Sw += np.cov(Xclass.T)

        #  1. Compute the center of the data, m
        #  2. Compute the center of individual classes, mc.
        #  3. Compute the variance of mc over all classes with m as the center, namely \sum (mc - m)(mc - m)^T
        # mu = X.mean(axis=0)
        for i, yc in enumerate(yclass):
            mc = X[y == yc].mean(axis=0)
            Sb += np.outer((mc - self.mean), (mc - self.mean).T)

        lam, v = sparse.linalg.eigs(Sb, M=Sw, k=self.n_components, which="LM")

        return self

    def transform(self, X: np.ndarray) -> np.ndarray:
        """
        Apply dimensionality reduction to X.

        X is projected on the first principal components previously extracted from a training set.

        Parameters
        ----------
        X : ndarray of shape (n_samples, n_features)
            New data, where n_samples is the number of samples
            and n_features is the number of features.

        Returns
        -------
        X_new : ndarray of shape (n_samples, n_components)
            Transformed values.
        """
        X_new = X @ self.components

        return X_new


# TODO: Generating adversarial examples for PCA.
# We will generate adversarial examples for PCA. The adversarial examples are generated by creating two well-separated clusters in a 2D space.
# Then, we will apply PCA to the data and check if the clusters are still well-separated in the transformed space.
# Your task is to generate adversarial examples for PCA, in which
# the clusters are well-separated in the original space, but not in the PCA space. The separability of the clusters will be measured by the
# K-means clustering algorithm in the test script.
#
# Hint:
# - You can place the two clusters wherever you want in a 2D space.
# - For example, you can use `np.random.multivariate_normal` to generate the samples in a cluster. Repeat this process for both clusters and
# concatenate the samples to create a single dataset.
# - You can set any covariance matrix, mean, and number of samples for the clusters.


class AdversarialExamples:
    def __init__(self) -> None:
        pass

    def pca_adversarial_data(self, n_samples, n_features):
        """Generate adversarial examples for PCA

        Parameters
        ----------
        n_samples : int
            The number of samples to generate.
        n_features : int
            The number of features.

        Returns
        -------
        X: ndarray of shape (n_samples, n_features)
            Transformed values.

        y: ndarray of shape (n_samples,)
            Cluster IDs. y[i] is the cluster ID of the i-th sample.

        """
        mean1 = [3, 10]
        cov1 = [[6, -3], [-3, 3.5]]
        mean2 = [1, 3]
        cov2 = [[0, 1], [2, 2]]

        X1 = np.random.multivariate_normal(mean1, cov1, n_samples)
        X2 = np.random.multivariate_normal(mean2, cov2, n_samples)
        X = np.concatenate((X1, X2))
        y = np.concatenate((np.zeros(n_samples), np.ones(n_samples)))

        model = PrincipalComponentAnalysis(n_components=1)
        X_transformed = model.fit_transform(X)

        return X_transformed, y


# %%
